version: '3.7'

services:
  # Vault
  vault:
    hostname: vault
    image: arti.dev.cray.com/third-party-docker-stable-local/vault:1.5.5
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=hms
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
  # The KV enabler comes from:
  # https://stash.us.cray.com/projects/HMS/repos/hms-redfish-translation-layer/browse/vault-kv-enabler.dockerfile
  vault-kv-enabler:
    #TODO: need to build and push this image to Artifactory
    image: dtr.dev.cray.com/hms/vault-kv-enabler:1.4.0
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - KV_STORES=hms-creds,reds-creds,pdu-creds
    depends_on:
      - vault

  # HSM
  zookeeper:
    #TODO: need to push this image to Artifactory
    image: dtr.dev.cray.com/confluentinc/cp-zookeeper:5.4.0
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    #TODO: need to push this image to Artifactory
    image: dtr.dev.cray.com/confluentinc/cp-kafka:5.4.0
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  hmsds-postgres:
    hostname: hmsds-postgres
    image: arti.dev.cray.com/third-party-docker-stable-local/postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=hmsdsuser
      - POSTGRES_USER=hmsdsuser
      - POSTGRES_DB=hmsds
  cray-smd-init:
    image: arti.dev.cray.com/csm-docker-master-local/cray-smd:latest
    environment:
      - SMD_DBHOST=hmsds-postgres
      - SMD_DBPORT=5432
    depends_on:
      - hmsds-postgres
    command: /entrypoint.sh smd-init
  cray-smd:
    image: arti.dev.cray.com/csm-docker-master-local/cray-smd:latest
    environment:
      - POSTGRES_HOST=hmsds-postgres
      - POSTGRES_PORT=5432
      - RF_MSG_HOST=kafka:9092:cray-dmtf-resource-event
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_JWT_FILE=configs/token
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - VAULT_KEYPATH=hms-creds
      - SMD_WVAULT=true
      - SMD_RVAULT=true
    hostname: cray-smd
    depends_on:
      - cray-smd-init
      - vault
    ports:
      - "27779:27779"

  # SLS
  sls-postgres:
    hostname: sls-postgres
    image: arti.dev.cray.com/third-party-docker-stable-local/postgres:11-alpine
    environment:
      - POSTGRES_USER=slsuser
      - POSTGRES_DB=sls
      - POSTGRES_HOST_AUTH_METHOD=trust
  sls-init:
    image: arti.dev.cray.com/csm-docker-master-local/cray-sls:latest
    command: ["sls-init"]
    environment:
      - POSTGRES_HOST=sls-postgres
      - DBOPTS=sslmode=disable
      - DBUSER=slsuser
    depends_on:
      - sls-postgres
  sls:
    image: arti.dev.cray.com/csm-docker-master-local/cray-sls:latest
    environment:
      - POSTGRES_HOST=sls-postgres
      - DBOPTS=sslmode=disable
      - DBUSER=slsuser
      - CRAY_VAULT_AUTH_PATH=auth/token/create
      - CRAY_VAULT_ROLE_FILE=configs/namespace
      - CRAY_VAULT_JWT_FILE=configs/token
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=hms
      - VAULT_KEYPATH=hms-creds
    ports:
      - "8376:8376"
    depends_on:
      - sls-postgres
      - sls-init
      - vault