apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hms-discovery
  labels:
    app: hms-discovery
spec:
  suspend: false
  schedule: "*/3 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 300
      template:
        metadata:
          labels:
            app: hms-discovery
            cronjob-name: hms-discovery
        spec:
          containers:
            - name: hms-discovery
              imagePullPolicy: Always
              image: "{{ include "cray-hms-discovery.image-prefix" . }}cray/hms-discovery:{{ include "cray-hms-discovery.imageTag" . }}"
              env:
                - name: SLS_URL
                  value: "http://cray-sls"
                - name: HSM_URL
                  value: "http://cray-smd"
                - name: DISCOVER_RIVER
                  value: "true"
                - name: DISCOVER_MOUNTAIN
                  value: "true"
                - name: BOOT_NEW_RIVER_NODES
                  value: "false"

                - name: VAULT_ADDR
                  value: "http://cray-vault.vault:8200"
                - name: VAULT_SKIP_VERIFY
                  value: "true"
                - name: VAULT_BASE_PATH
                  value: "secret"
          restartPolicy: Never
